/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ResCust;

/**
 *
 * @author Whelan
 */
public class ReservationViewB extends javax.swing.JPanel {

    /**
     * Creates new form ReservationView
     */
    public ReservationViewB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGrid = new javax.swing.JPanel();
        pnlTopBtn = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        editValButton = new javax.swing.JButton();
        bottomButtonPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnlGridLayout = new javax.swing.GroupLayout(pnlGrid);
        pnlGrid.setLayout(pnlGridLayout);
        pnlGridLayout.setHorizontalGroup(
            pnlGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlGridLayout.setVerticalGroup(
            pnlGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(pnlGrid, java.awt.BorderLayout.CENTER);

        pnlTopBtn.setLayout(new javax.swing.BoxLayout(pnlTopBtn, javax.swing.BoxLayout.LINE_AXIS));

        homeButton.setText("Home");
        pnlTopBtn.add(homeButton);

        editValButton.setText("Edit Values");
        pnlTopBtn.add(editValButton);

        add(pnlTopBtn, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout bottomButtonPanelLayout = new javax.swing.GroupLayout(bottomButtonPanel);
        bottomButtonPanel.setLayout(bottomButtonPanelLayout);
        bottomButtonPanelLayout.setHorizontalGroup(
            bottomButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bottomButtonPanelLayout.setVerticalGroup(
            bottomButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(bottomButtonPanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    public void registerListener(ReservationControl controller) {
        //btnAddStudent.addActionListener(controller);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomButtonPanel;
    private javax.swing.JButton editValButton;
    private javax.swing.JPanel pnlGrid;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel pnlTopBtn;
    // End of variables declaration//GEN-END:variables
}
