
package home;

/**
 *
 * @author Yeejkoob Thao
 */
import java.awt.CardLayout;
import java.awt.event.ActionListener;
import javax.swing.*;
public class HomeView extends javax.swing.JPanel {

    private JPanel allPanelContainer;
    /**
     * Creates new form HomeView
     */
    public HomeView(JPanel panelContainer) {
        this.allPanelContainer = panelContainer;
        initComponents();
    }

    public JLabel getUserLevelLabel() {
    
        return userLevelLabel;
            
    }
    
    public JButton getInventoryMngButton() {
    
        return inventoryMngButton;
    
    }
    
    public JButton getStaffMngButton() {
    
        return staffMngButton;
        
    }
    
    public JButton getFinanceMngButton() {
    
        return financeMngButton;
    
    }
    
    public JButton getUserMngButton() {
    
        return userMngButton;
    
    }
    
    public void goToLoginView() {
        CardLayout cardLayout = (CardLayout) allPanelContainer.getLayout();
        cardLayout.show(allPanelContainer, "Login View");
    }
    
    public void goToUserManagementView() {
        CardLayout cardLayout = (CardLayout) allPanelContainer.getLayout();
        cardLayout.show(allPanelContainer, "User Management View");
    }
    
    public void goToStaffManagementView() {
        CardLayout cardLayout = (CardLayout) allPanelContainer.getLayout();
        cardLayout.show(allPanelContainer, "Staff Management View");
    }
    
    void addLogoutButtonListener(ActionListener listenForLogout) {
        logoutButton.addActionListener(listenForLogout);
    }
    
    void addUserManagementButtonListener(ActionListener listenForUserManagement) {
        userMngButton.addActionListener(listenForUserManagement);
    }
    
    void addStaffManagementButtonListener(ActionListener listenForStaffManagement) {
        staffMngButton.addActionListener(listenForStaffManagement);
    }
    
    void displayErrorMessage(String errorMessage) {
        JOptionPane.showMessageDialog(this, errorMessage);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        roomMngButton = new javax.swing.JButton();
        ResCustMngButton = new javax.swing.JButton();
        inventoryMngButton = new javax.swing.JButton();
        staffMngButton = new javax.swing.JButton();
        financeMngButton = new javax.swing.JButton();
        userMngButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        userLevelLabel = new javax.swing.JLabel();

        jButton7.setText("jButton7");

        title.setText("Hotel Management System: Home");

        roomMngButton.setText("Room Management");
        roomMngButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomMngButtonActionPerformed(evt);
            }
        });

        ResCustMngButton.setText("Reservation/Customer Management");

        inventoryMngButton.setText("Inventory Management");

        staffMngButton.setText("Staff Management");

        financeMngButton.setText("Finance Management");

        userMngButton.setText("User Management");

        logoutButton.setText("Logout");

        userLevelLabel.setText("Userlevel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ResCustMngButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomMngButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inventoryMngButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(staffMngButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(financeMngButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userMngButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logoutButton)
                        .addGap(209, 209, 209))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(50, 50, 50)
                        .addComponent(userLevelLabel)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title))
                    .addComponent(userLevelLabel))
                .addGap(18, 18, 18)
                .addComponent(roomMngButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResCustMngButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryMngButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffMngButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(financeMngButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userMngButton)
                .addGap(18, 18, 18)
                .addComponent(logoutButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void roomMngButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomMngButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomMngButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResCustMngButton;
    private javax.swing.JButton financeMngButton;
    private javax.swing.JButton inventoryMngButton;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton roomMngButton;
    private javax.swing.JButton staffMngButton;
    private javax.swing.JLabel title;
    private javax.swing.JLabel userLevelLabel;
    private javax.swing.JButton userMngButton;
    // End of variables declaration//GEN-END:variables
}
