/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Finance;

import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.*;
/**
 *
 * @author Yeejkoob Thao
 */
public class FinanceView extends javax.swing.JPanel {

    /**
     * Creates new form FinanceView
     */
    private JPanel allPanelContainer;
    public FinanceView(JPanel panel) {
        allPanelContainer = panel;
        initComponents();
        
    }
    
    @Override
    public void paintComponent(Graphics g) {
        ImageIcon background = new ImageIcon(getClass().getResource("/Images/ReceptionRoom.jpg"));
        Image image = background.getImage();
        super.paintComponent(g);
        g.drawImage(image, 0, 0, this);
    }
    
    public JTextField getUserDefinedExpensesField() {
        return this.userDefinedExpensesField;
    }
    
    public JTextField getUserDefinedRevenueField() {
        return this.userDefinedRevenueField;
    }
    
    public JTextField getYearlyProfitField() {
        return this.yearlyProfitField;
    }
    
    public JComboBox getFinanceYearComboBox() {
        return this.financeYear;
    }
    
    public JTable getFinanceTable() {
        return this.financeTable;
    }

    public void goToHomeView() {
        CardLayout cardLayout = (CardLayout) allPanelContainer.getLayout();
        cardLayout.show(allPanelContainer, "Home View");
    }
    
    void addCalculateButtonListener(ActionListener listenForCalculateButton) {
        calculateButton.addActionListener(listenForCalculateButton);
    }
    
    void addHomeButtonListener(ActionListener listenForHomeButton) {
        homeButton.addActionListener(listenForHomeButton);
    }
    
    void addDeleteButtonListener(ActionListener listenForDeleteButton) {
        deleteButton.addActionListener(listenForDeleteButton);
    }
    
    void addAddNewFinanceYearButtonListener(ActionListener listenForAddNewFinanceYear) {
        addNewFinanceYearButton.addActionListener(listenForAddNewFinanceYear);
    }
    
    void displayErrorMessage(String errorMessage) {
        
        JOptionPane.showMessageDialog(this, errorMessage);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        financeTable = new javax.swing.JTable();
        financeYear = new javax.swing.JComboBox<>();
        titleLabel = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        userDefinedRevenueLabel = new javax.swing.JLabel();
        userDefinedExpensesLabel = new javax.swing.JLabel();
        yearlyProfitLabel = new javax.swing.JLabel();
        userDefinedRevenueField = new javax.swing.JTextField();
        userDefinedExpensesField = new javax.swing.JTextField();
        yearlyProfitField = new javax.swing.JTextField();
        addNewFinanceYearButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        calculateButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        financeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(financeTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 998;
        gridBagConstraints.ipady = 283;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 0, 0, 0);
        add(jScrollPane1, gridBagConstraints);

        financeYear.setFont(new java.awt.Font("Kalinga", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 91;
        gridBagConstraints.insets = new java.awt.Insets(6, 19, 4, 4);
        add(financeYear, gridBagConstraints);

        titleLabel.setFont(new java.awt.Font("Kalinga", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 0, 51));
        titleLabel.setText("Finance Management");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(titleLabel, gridBagConstraints);

        homeButton.setFont(new java.awt.Font("Kalinga", 0, 18)); // NOI18N
        homeButton.setText("Home");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.insets = new java.awt.Insets(25, 15, 16, 0);
        add(homeButton, gridBagConstraints);

        userDefinedRevenueLabel.setFont(new java.awt.Font("Kalinga", 1, 18)); // NOI18N
        userDefinedRevenueLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UserDefinedRevenue.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 48, 0, 0);
        add(userDefinedRevenueLabel, gridBagConstraints);

        userDefinedExpensesLabel.setFont(new java.awt.Font("Kalinga", 1, 18)); // NOI18N
        userDefinedExpensesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UserDefinedExpenses.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 48, 0, 0);
        add(userDefinedExpensesLabel, gridBagConstraints);

        yearlyProfitLabel.setFont(new java.awt.Font("Kalinga", 1, 18)); // NOI18N
        yearlyProfitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/YearlyProfit.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 48, 0, 0);
        add(yearlyProfitLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 122;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 84, 0, 598);
        add(userDefinedRevenueField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 122;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 84, 0, 598);
        add(userDefinedExpensesField, gridBagConstraints);

        yearlyProfitField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 122;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 84, 0, 598);
        add(yearlyProfitField, gridBagConstraints);

        addNewFinanceYearButton.setFont(new java.awt.Font("Kalinga", 0, 18)); // NOI18N
        addNewFinanceYearButton.setText("Add New Finance Year");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 15, 16, 0);
        add(addNewFinanceYearButton, gridBagConstraints);

        deleteButton.setFont(new java.awt.Font("Kalinga", 0, 18)); // NOI18N
        deleteButton.setText("Delete Year");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(deleteButton, gridBagConstraints);

        calculateButton.setFont(new java.awt.Font("Kalinga", 0, 18)); // NOI18N
        calculateButton.setText("Calculate");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 600);
        add(calculateButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewFinanceYearButton;
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTable financeTable;
    private javax.swing.JComboBox<String> financeYear;
    private javax.swing.JButton homeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField userDefinedExpensesField;
    private javax.swing.JLabel userDefinedExpensesLabel;
    private javax.swing.JTextField userDefinedRevenueField;
    private javax.swing.JLabel userDefinedRevenueLabel;
    private javax.swing.JTextField yearlyProfitField;
    private javax.swing.JLabel yearlyProfitLabel;
    // End of variables declaration//GEN-END:variables
}
